### ISSUE TITLE
[question] javascript runtime?

### ISSUE THREAD

**Issue by u007** [headzoo/surf#41]
Hi,

does it run javascript after loading the page?
thanks

**Comment by Ovid** [comment]
No, it does not.

**Comment by mdaliyan** [comment]
Surf is so fast and uses very low resources. but the problem is web is going towards the point that you can see AngularJS, Vue, React, Ember and so many more frameworks everywhere. not being able to render those pages by surf, makes me use phantomjs, that is too slow and eats resources like a whale.

May you please add surf the ability to run JavaScript on the page? (width some option to make it enabled or disabled)

May you please consider this feature?

**Comment by yalay** [comment]
me too.

**Comment by Splizard** [comment]
This is possible, just need to create a DOM and integrate https://github.com/robertkrimen/otto

**Comment by lxt2** [comment]
The thing is, it's a LOT more complicated then that. Otto is a (partial) javascript interpreter, but you need to handle the DOM and all of the quirks of a browser. It's outside of the scope of what Surf does. I'd suggest looking at something like Chrome's new Headless mode.
